package banque.persistance.entities;
// Generated 21 avr. 2021 à 13:52:46 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TClient generated by hbm2java
 */
@Entity
@Table(name = "T_CLIENT", schema = "BDBANK")
public class TClient implements java.io.Serializable {

	private BigDecimal CId;
	private String CNom;
	private Set<TCompte> TComptes = new HashSet<TCompte>(0);

	public TClient() {
	}

	public TClient(BigDecimal CId) {
		this.CId = CId;
	}

	public TClient(BigDecimal CId, String CNom, Set<TCompte> TComptes) {
		this.CId = CId;
		this.CNom = CNom;
		this.TComptes = TComptes;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "CLIENT_SEQ")
    @SequenceGenerator(name="T_CLIENT_SEQ", sequenceName = "T_CLIENT_SEQ", allocationSize = 1)
	@Column(name = "C_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getCId() {
		return this.CId;
	}

	public void setCId(BigDecimal CId) {
		this.CId = CId;
	}

	@Column(name = "C_NOM", length = 20)
	public String getCNom() {
		return this.CNom;
	}

	public void setCNom(String CNom) {
		this.CNom = CNom;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "TClient")
	public Set<TCompte> getTComptes() {
		return this.TComptes;
	}

	public void setTComptes(Set<TCompte> TComptes) {
		this.TComptes = TComptes;
	}

}
