package banque.persistance.entities;
// Generated 21 avr. 2021 à 13:52:46 by Hibernate Tools 5.0.6.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TCompte generated by hbm2java
 */
@Entity
@Table(name = "T_COMPTE", schema = "BDBANK")
public class TCompte implements java.io.Serializable {

	private BigDecimal coId;
	private TClient TClient;
	private String coNom;

	public TCompte() {
	}

	public TCompte(BigDecimal coId) {
		this.coId = coId;
	}

	public TCompte(BigDecimal coId, TClient TClient, String coNom) {
		this.coId = coId;
		this.TClient = TClient;
		this.coNom = coNom;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "COMPTE_SEQ")
    @SequenceGenerator(name="T_COMPTE_SEQ", sequenceName = "T_COMPTE_SEQ", allocationSize = 1)
	@Column(name = "CO_ID", unique = true, nullable = false, length = 20)
	public BigDecimal getCoId() {
		return this.coId;
	}

	public void setCoId(BigDecimal coId) {
		this.coId = coId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "FK_C_ID")
	public TClient getTClient() {
		return this.TClient;
	}

	public void setTClient(TClient TClient) {
		this.TClient = TClient;
	}

	@Column(name = "CO_NOM", length = 20)
	public String getCoNom() {
		return this.coNom;
	}

	public void setCoNom(String coNom) {
		this.coNom = coNom;
	}

}
